### ISSUE TITLE
Notices generated in imagecolorat(), line 4579

### ISSUE THREAD

**Issue by czachor** [verot/class.upload.php#101]
Sometimes when I'm trying to upload an image, a notice is generated:
`Notice:  imagecolorat(): 821,0 is out of bounds in /www/foobar_site/vendor/verot/class.upload.php/src/class.upload.php on line 4759`
(notice is generated for each image pixel). The code is trying to loop through non existing image pixels.

Uploaded image:
JPG, saved in photoshop using 'save for web' option, 821*305px. If you need, it's [here](https://www.dropbox.com/s/rm83dw7905h6i5q/trombosis.jpg?dl=0).
When `$upload->image_x` value is bigger (eg. 822) than uploaded image width (821), the notice is generated.
Solution: set `$upload->image_x` to <= 821.

I suppose it could be connected with `image_resize` (true) or `image_ratio_*` settings.

PHP (tested): 7.1, 7.2, GD ver: bundled (2.1.0 compatible).
class.upload.php ver: latest - 0.35dev, using composer

My processing code:

            $upload = new upload($_FILES['file2upload']);

            if ($upload->uploaded) {
                $upload->file_new_name_body = 'random_string_here';
                $upload->allowed = 'image/*';

                $upload->image_resize = true;
                $upload->image_ratio_y = true;
                $upload->image_x = 822; // here!! should be 821 or lower

                $upload->process('upload/');

                if (!$upload->processed) {
                    echo 'ops';
                } else {
                    echo 'uploaded: ' . $upload->file_dst_name;
                }
            }

BTW it's little confusing, line 4759 is responsible for converting image to BMP, but I don't want to do it.

**Comment by verot** [comment]
Thank you for your precise bug report. And indeed, you are right, there was a bug. `image_x` was producing PHP notices only for value 822 (not 821, the size of your image, and not 823, or 824, etc...). It is because if you change the width by one pixel, the height may not change at all. And in that case, the resizing code wasn't called, thus producing out of bound errors later in the code. If you were to change the width by more than 1 pixel, it is likely that the height would change also, triggering resizing, and avoiding out of bound errors. So thank you for finding out this edge case.

Fix is on master 6a4bcb538

And regarding line 4759, it is for BMP and JPEG (see line above). In fact for non-transparent images. So it is normal that this code is called for your JPEG image.
