### ISSUE TITLE
Xls files saving with .txt extension

### ISSUE THREAD

**Issue by Lovattows** [verot/class.upload.php#98]
Hello everyone, i'm trying to upload some files with .xls extension, and inside my folder they are saving that .xls files with .txt extension. Need advice please.

**Comment by verot** [comment]
Check out the log produced by the class. Probably there is an issue while detecting MIME types. Please read the documentation accordingly.

**Comment by Lovattows** [comment]
Log output this:
system information
- class version : 0.34dev
- operating system : Linux
- PHP version : 5.6.37-1+ubuntu16.04.1+deb.sury.org+1
- GD version : 2.2.5
- supported image types : png jpg gif bmp
- open_basedir : no restriction
- upload_max_filesize : 64M (67108864 bytes)
- language : en_GB
source is a local file /tmp/phpsT7DZl-tmp
- local file OK
determining MIME type
- Checking MIME type with Fileinfo PECL extension
    MAGIC path will not be used
    MIME type detected as application/vnd.ms-office; charset=binary by Fileinfo PECL extension
- MIME validated as application/vnd.ms-office
source variables
- You can use all these before calling process()
    file_src_name : phpsT7DZl-tmp
    file_src_name_body : phpsT7DZl-tmp
    file_src_name_ext :
    file_src_pathname : /tmp/phpsT7DZl-tmp
    file_src_mime : application/vnd.ms-office
    file_src_size : 52736 (max= 67108864)
    file_src_error : 0
process file to /srv/uploads/helpdesk/2018/09/
- file size OK
- script renamed as phpsT7DZl-tmp.txt!

**Comment by verot** [comment]
I see... So basically, you are (as per the log) uploading a file with no extension. The class detects the MIME as being `application/vnd.ms-office`

But, because of the option `no_script`, because there is no file extension, the class tries to add the correct extension. In the list of supported MIME types, `application/vnd.ms-office` is not present (we have `application/vnd.ms-excel` for XLS files), and so it adds the extension _.txt_.

You can try to deactivate the option `no_script` to prevent this behaviour. But in fact, your upload should send the correct file name and file extension (which is not the case in your log).

Alternatively, you can try to replace the MIME type for the extension XLS (so to have `'xls' => 'application/vnd.ms-office'`)

**Comment by Lovattows** [comment]
Thank you so much, added the MIME type 'xls' => 'application/vnd.ms-office' and worked as well.
PS: i can add multiple xls mime_types?
'xls' => 'application/vnd.ms-excel',
'xls' => 'application/vnd.ms-office',

**Comment by verot** [comment]
No, you cannot add several ones, as it is a PHP indexed array. Only the last _xls_ key will be taken into account.

**Comment by Lovattows** [comment]
Ok, thank you so much.
